type dbObject = {
    id: number;
    isChecked: boolean;
}


type dbObjectArray = dbObject[]


export let dummyData: dbObjectArray = [
    { id: 1, isChecked: false },
    { id: 2, isChecked: false },
    { id: 3, isChecked: false },
    { id: 4, isChecked: false },
    { id: 5, isChecked: false },
    { id: 6, isChecked: false },
    { id: 7, isChecked: false },
    { id: 8, isChecked: false },
    { id: 9, isChecked: false },
    { id: 10, isChecked: false },
    { id: 11, isChecked: false },
    { id: 12, isChecked: false },
    { id: 13, isChecked: false },
    { id: 14, isChecked: false },
    { id: 15, isChecked: false },
    { id: 16, isChecked: false },
    { id: 17, isChecked: false },
    { id: 18, isChecked: false },
    { id: 19, isChecked: false },
    { id: 20, isChecked: false },
    { id: 21, isChecked: false },
    { id: 22, isChecked: false },
    { id: 23, isChecked: false },
    { id: 24, isChecked: false },
    { id: 25, isChecked: false },
    { id: 26, isChecked: false },
    { id: 27, isChecked: false },
    { id: 28, isChecked: false },
    { id: 29, isChecked: false },
    { id: 30, isChecked: false },
    { id: 31, isChecked: false },
    { id: 32, isChecked: false },
    { id: 33, isChecked: false },
    { id: 34, isChecked: false },
    { id: 35, isChecked: false },
    { id: 36, isChecked: false },
    { id: 37, isChecked: false },
    { id: 38, isChecked: false },
    { id: 39, isChecked: false },
    { id: 40, isChecked: false },
    { id: 41, isChecked: false },
    { id: 42, isChecked: false },
    { id: 43, isChecked: false },
    { id: 44, isChecked: false },
    { id: 45, isChecked: false },
    { id: 46, isChecked: false },
    { id: 47, isChecked: false },
    { id: 48, isChecked: false },
    { id: 49, isChecked: false },
    { id: 50, isChecked: false },
    { id: 51, isChecked: false },
    { id: 52, isChecked: false },
    { id: 53, isChecked: false },
    { id: 54, isChecked: false },
    { id: 55, isChecked: false },
    { id: 56, isChecked: false },
    { id: 57, isChecked: false },
    { id: 58, isChecked: false },
    { id: 59, isChecked: false },
    { id: 60, isChecked: false },
    { id: 61, isChecked: false },
    { id: 62, isChecked: false },
    { id: 63, isChecked: false },
    { id: 64, isChecked: false },
    { id: 65, isChecked: false },
    { id: 66, isChecked: false },
    { id: 67, isChecked: false },
    { id: 68, isChecked: false },
    { id: 69, isChecked: false },
    { id: 70, isChecked: false },
    { id: 71, isChecked: false },
    { id: 72, isChecked: false },
    { id: 73, isChecked: false },
    { id: 74, isChecked: false },
    { id: 75, isChecked: false },
    { id: 76, isChecked: false },
    { id: 77, isChecked: false },
    { id: 78, isChecked: false },
    { id: 79, isChecked: false },
    { id: 80, isChecked: false },
    { id: 81, isChecked: false },
    { id: 82, isChecked: false },
    { id: 83, isChecked: false },
    { id: 84, isChecked: false },
    { id: 85, isChecked: false },
    { id: 86, isChecked: false },
    { id: 87, isChecked: false },
    { id: 88, isChecked: false },
    { id: 89, isChecked: false },
    { id: 90, isChecked: false },
    { id: 91, isChecked: false },
    { id: 92, isChecked: false },
    { id: 93, isChecked: false },
    { id: 94, isChecked: false },
    { id: 95, isChecked: false },
    { id: 96, isChecked: false },
    { id: 97, isChecked: false },
    { id: 98, isChecked: false },
    { id: 99, isChecked: false },
    { id: 100, isChecked: false }
];

export function updateCheckbox(id: number, newValue: boolean) {
    dummyData = dummyData.map(item => item.id === id ? { ...item, isChecked: newValue } : item)
    return;
}